@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="page-title category-title">
                <h1 class="title-head"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Privacy Policy</font></font></h1>
            </div>
            <div class="content-page rte">
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1. Purpose and scope of collection</font></font></span></span></span></b></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Thank you for visiting our website. To use the services on the website, you may be required to register personal information with us such as:</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">- Full name, contact address</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">- Email, mobile phone number</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">We may also collect information about the number of visits to our website including the number of pages you view, the number of links you click and other information related to connecting to the address lemavietnam.vn…</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">2. Scope of information use</font></font></span></span></span></b></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Halafruit.vn collects and uses personal information for appropriate purposes and in full compliance with this "privacy policy". We only use your information within the company or may disclose it to third parties such as agents and other service providers to provide the best and most optimal service to you.</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">When necessary, we may use this information to contact you directly, such as sending open letters, orders, thank you letters, technical and security information, promotional information, information about new products and services, etc.</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">3. Information storage time</font></font></span></span></span></b></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Your information will be stored in our company's internal system until you request to cancel the information provided.</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">4. Address of the unit collecting and managing personal information</font></font></span></span></span></b></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><font color="#000000" face="Times New Roman, serif"><span style="font-size: 16px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">IMPORTED FRUIT STORE - HALAFRUIT</font></font></span></font></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Address: No. 95 Xuan La, Tay Ho, Hanoi</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Phone: 0978.870.263</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">5. Means and tools for users to access and edit personal data</font></font></span></span></span></b></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">If you want to edit your personal information, please contact our customer service hotline via phone number: 0944.683.689; 0862.593.599 or via email address:&nbsp; </font></font><a href="mailto:lemavietnam@mich.com.vn"><span style="color:#575454"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">H</font></font></span></a><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"> oa263mta@gmail.com</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><b><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">6. Commitment to protect customer's personal information</font></font></span></span></span></b></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">We are committed to protecting your information in every possible way according to our personal information protection policy.</font></font></span></span></span></span></span></span></span></p>
                <p style="margin-bottom:15px; text-align:justify"><span style="font-size:11pt"><span style="background:white"><span style="line-height:normal"><span style="font-family:Calibri,sans-serif"><span style="font-size:12.0pt"><span style="font-family:&quot;Times New Roman&quot;,serif"><span style="color:black"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">We absolutely do not share your information with any other company or third party except for agents and suppliers involved in providing services to you.</font></font></span></span></span></span></span></span></span></p>
            </div>
        </div>
    </div>
</div>
@endsection